### ISSUE TITLE
cudmore -todo

### ISSUE THREAD

**Issue by cudmore** [mapmanager/PyMapManager#15]
July 11, 2023

- [x] move left/right scatter into line plot (move out of base plot)

- [x] add options to base plot to self._showSymbols, self._showPen

- [x] when plotting lines with pyqtgraph setdata(), set `connect` to an ndarray of (1,0) where 1 means connect to next. Finite connect="finite" is not sufficient

- [ ] re-implement editing in annotationPlot by implementing slot_Added, slot_deleted, slot_modified. Basically have to manage the _labels and _spineLine (add, delete update).
    Nope, instead we will extend class selection to incude 'added', 'deleted', 'edited'!

- [ ] in stack widget, toggle boolean variable when we programmatically show hide elements. Things like annotation list, segment list, etc. See stackWidget toggleView().
    Likewise, when we bring up interface, toggle the views based on display options.

- [ ] In stack widget, when we turn off the tracing, we need to hide all (spine) labels

- [ ] In stack widget, when we are not showing image, the scatter plots of annotations auto zoom. Add code to make the x/y zoom fixed based on the size of the hypothetical image.

- [ ] On cancel selection, be sure to cancel all selection including spine ROIs for (spine, segment, background spine, background segment)
